markdown: kramdown
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
title: arXiv Radar
description: An intelligent system that monitors and curates cutting-edge AI research papers from arXiv.
baseurl: "/arXivRadar"
kramdown:
  input: GFM
  hard_wrap: false
relative_links:
  enabled: true
  collections: true