name: Update Papers and Generate Web View

on:
  # label:
  #   types:
  #     - created # for test
  schedule:
    - cron: '30 16 * * *' # 00:30 Singapore time every day
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pages: write

jobs:
  update_daily_papers:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: List files
      run: |
        ls -l

    - name: Install dependencies
      run: |
        pip3 install -r ./requirements.txt

    - name: Update papers
      run: |
        python3 main.py

    - name: Generate web view
      run: |
        mkdir -p .web
        cp -r papers .web/
        cp README.md .web/index.md
        echo "theme: jekyll-theme-cayman" > .web/_config.yml

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .web
        force_orphan: true

    - name: Commit and push changes
      uses: github-actions-x/commit@v2.9
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'master'
        commit-message: '✏️ Update papers automatically'
        files: 'README.md papers/**/*'
        name: XinLi
        email: lixin.1997.lixin@gmail.com

    # - name: Create an issue to notify
    #   uses: JasonEtco/create-an-issue@v2
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
