name: Update

on:
  # label:
  #   types:
  #     - created # for test
  # schedule:
  #     - cron: '30 16 * * 0-4' # 00:30 Beijing time every Monday to Friday
  workflow_dispatch:

permissions:
  contents: write
  issues: write 

jobs:
  update_daily_papers:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: List files
      run: |
        ls -l

    - name: Install dependencies
      run: |
        pip3 install -r ./requirements.txt

    - name: Update papers
      run: |
        python3 main.py

    - name: Commit and push changes
      uses: github-actions-x/commit@v2.9
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'master'
        commit-message: '✏️ Update papers automatically.'
        files: 'README.md papers/**/*'
        name: XinLi
        email: lixin.1997.lixin@gmail.com

    # - name: Create an issue to notify
    #   uses: JasonEtco/create-an-issue@v2
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
